import { useState, useEffect } from 'react';
import { fetchMyPayslips } from '@/services/api';
import toast from 'react-hot-toast';
import { 
  HiOutlineDocumentText, 
  HiOutlineXMark, 
  HiOutlinePlus,
  HiOutlineInformationCircle
} from 'react-icons/hi2';
import { useAuth } from '@/context/AuthContext';

const MyPayslips = () => {
  const [payslips, setPayslips] = useState([]);
  const [loading, setLoading] = useState(true);
  const [selectedPayslip, setSelectedPayslip] = useState(null);
  const [showViewModal, setShowViewModal] = useState(false);
  const { user } = useAuth();

  useEffect(() => {
    loadPayslips();
  }, []);

  const loadPayslips = async () => {
    try {
      const res = await fetchMyPayslips();
      setPayslips(res.data);
    } catch (err) {
      toast.error('Could not load your payslips');
    } finally {
      setLoading(false);
    }
  };

  if (loading) return <div className="text-center py-20 text-slate-400 font-bold animate-pulse uppercase tracking-[0.2em]">Authenticating Secure Records...</div>;

  return (
    <div className="space-y-8 fade-in">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h1 className="text-3xl font-black text-slate-900 tracking-tight">Financial <span className="text-indigo-600">Records</span></h1>
          <p className="text-slate-500 mt-1 font-medium italic">Access and download your official monthly payslips</p>
        </div>
      </div>

      {payslips.length === 0 ? (
        <div className="glass-card p-12 text-center space-y-4 border-dashed border-2 border-slate-100">
          <div className="w-16 h-16 bg-slate-50 rounded-2xl flex items-center justify-center mx-auto text-slate-300">
            <HiOutlineInformationCircle className="w-8 h-8" />
          </div>
          <div>
            <p className="text-lg font-black text-slate-900 uppercase tracking-tight">No records published yet</p>
            <p className="text-sm text-slate-400 mt-1">Your monthly payslips will appear here once generated by HR.</p>
          </div>
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {payslips.map((slip) => (
            <div 
                key={slip._id} 
                className="glass-card p-6 group hover:border-indigo-500/30 transition-all cursor-pointer relative overflow-hidden active:scale-[0.98]"
                onClick={() => { setSelectedPayslip(slip); setShowViewModal(true); }}
            >
              <div className="flex items-center justify-between relative z-10">
                <div className="w-12 h-12 rounded-2xl bg-indigo-50 text-indigo-600 flex items-center justify-center group-hover:bg-indigo-600 group-hover:text-white transition-all shadow-sm">
                  <HiOutlineDocumentText className="w-6 h-6" />
                </div>
                <span className="text-[10px] font-black text-slate-300 uppercase tracking-widest group-hover:text-indigo-200">Official Record</span>
              </div>
              
              <div className="mt-6 relative z-10">
                <h3 className="text-xl font-black text-slate-900 group-hover:text-indigo-700 transition-colors uppercase tracking-tight">{slip.month}</h3>
                <div className="flex items-center gap-2 mt-2">
                    <span className="px-2 py-0.5 bg-slate-100 text-slate-500 rounded text-[10px] font-black uppercase tracking-widest">Net Salary</span>
                    <p className="text-sm font-black text-slate-700">₹ {slip.summary.netSalary.toLocaleString()}</p>
                </div>
              </div>

              <div className="mt-6 pt-6 border-t border-slate-50 flex items-center justify-between relative z-10">
                <button className="text-[11px] font-black text-indigo-600 uppercase tracking-widest flex items-center gap-2 hover:underline">
                    Download PDF
                    <HiOutlinePlus className="rotate-45 w-3 h-3" />
                </button>
                <p className="text-[10px] font-bold text-slate-400 italic">Issued on {new Date(slip.generatedDate).toLocaleDateString()}</p>
              </div>

              {/* Decorative Background Icon */}
              <HiOutlineDocumentText className="absolute -bottom-4 -right-4 w-24 h-24 text-slate-50 opacity-0 group-hover:opacity-100 transition-opacity" />
            </div>
          ))}
        </div>
      )}

      {/* Payslip Viewer Modal (Identical to Admin but User-Focused) */}
      {showViewModal && selectedPayslip && (
        <div className="fixed inset-0 z-[120] flex items-center justify-center p-4 bg-slate-900/90 backdrop-blur-xl overflow-y-auto">
          <div className="bg-white rounded-[32px] w-full max-w-4xl shadow-2xl relative overflow-hidden flex flex-col max-h-[95vh]">
             <div className="p-6 border-b border-slate-100 flex justify-between items-center bg-slate-50/50">
                <div className="flex items-center gap-4">
                    <div className="w-10 h-10 rounded-xl bg-indigo-600 flex items-center justify-center text-white shadow-lg shadow-indigo-100">
                        <HiOutlineDocumentText className="w-5 h-5" />
                    </div>
                    <div>
                        <h2 className="text-xl font-black text-slate-900 uppercase tracking-tight">Statement: {selectedPayslip.month}</h2>
                        <p className="text-[10px] font-black text-slate-400 uppercase tracking-widest">{user.name}</p>
                    </div>
                </div>
                <div className="flex items-center gap-3">
                    <button 
                        onClick={() => window.print()} 
                        className="px-6 py-2.5 bg-slate-900 text-white rounded-xl font-black text-xs uppercase tracking-widest hover:bg-indigo-600 transition-all flex items-center gap-2"
                    >
                        Print Statement
                    </button>
                    <button 
                        onClick={() => setShowViewModal(false)}
                        className="w-10 h-10 flex items-center justify-center rounded-xl bg-white text-slate-400 hover:text-slate-900 border border-slate-100"
                    >
                        <HiOutlineXMark className="w-6 h-6" />
                    </button>
                </div>
             </div>

             <div className="flex-1 overflow-y-auto p-4 md:p-12 bg-slate-200/30 custom-scrollbar">
                <div className="bg-white w-full max-w-2xl mx-auto shadow-xl min-h-[1050px] p-0 flex flex-col print:shadow-none print:max-w-full rounded-[2rem] overflow-hidden">
                    <div className="w-full h-32 bg-white flex items-center justify-center">
                        <img src="/src/assets/payslip_header.png" alt="Company Header" className="h-20 object-contain" />
                    </div>

                    <div className="p-8 md:p-14 space-y-12 flex-1">
                        <div className="text-center">
                            <h3 className="text-3xl font-black text-slate-900 underline underline-offset-8 decoration-indigo-200 uppercase">PAY SLIP</h3>
                            <p className="text-xs font-black text-slate-400 mt-4 italic uppercase tracking-widest">Statement for {selectedPayslip.month}</p>
                        </div>

                        <div className="grid grid-cols-1 md:grid-cols-2 gap-px bg-slate-100 border border-slate-100 rounded-2xl overflow-hidden shadow-sm">
                            {[
                                ['Employee Name', user.name],
                                ['Job Role', user.jobRole],
                                ['Department', user.department],
                                ['Joining Date', user.dateOfJoining ? new Date(user.dateOfJoining).toLocaleDateString() : 'N/A'],
                                ['Employee ID', user.employeeId],
                                ['Bank Details', `${user.bankName} - ${user.bankAccountNo}`],
                                ['Payable Days', selectedPayslip.daysPayable]
                            ].map(([label, value]) => (
                                <div key={label} className="bg-white p-4 flex flex-col sm:flex-row border-b sm:border-b-0 border-slate-50">
                                    <span className="w-full sm:w-1/2 text-[10px] font-black text-slate-400 uppercase tracking-widest mb-1 sm:mb-0">{label}</span>
                                    <span className="w-full sm:w-1/2 text-[11px] font-black text-slate-900 uppercase">{value}</span>
                                </div>
                            ))}
                        </div>

                        <div className="border border-slate-100 rounded-[28px] overflow-hidden">
                            <table className="w-full table-fixed divide-y divide-slate-100">
                                <thead className="bg-slate-50">
                                    <tr className="divide-x divide-slate-100">
                                        <th className="p-4 text-left text-[11px] font-black text-slate-400 uppercase tracking-widest pl-6">Earnings</th>
                                        <th className="p-4 text-right text-[11px] font-black text-slate-400 uppercase tracking-widest pr-6">Amount</th>
                                        <th className="p-4 text-left text-[11px] font-black text-slate-400 uppercase tracking-widest pl-6">Deductions</th>
                                        <th className="p-4 text-right text-[11px] font-black text-slate-400 uppercase tracking-widest pr-6">Amount</th>
                                    </tr>
                                </thead>
                                <tbody className="divide-y divide-slate-50">
                                    {[
                                        ['basicSalary', 'Basic Salary', 'tds', 'TDS'],
                                        ['houseRentAllowance', 'HRA', 'professionalTax', 'Prof Tax'],
                                        ['specialAllowance', 'Special', 'pfEmployerContribution', 'PF (Emp)'],
                                        ['leaveTravelAllowance', 'LTA', 'esicEmployerContribution', 'ESIC (Emp)'],
                                        ['medicalAllowance', 'Medical', 'salaryDeduction', 'Other Ded']
                                    ].map(([eK, eL, dK, dL], idx) => (
                                        <tr key={idx} className="divide-x divide-slate-50">
                                            <td className="p-4 pl-6 text-[11px] font-bold text-slate-600 uppercase">{eL}</td>
                                            <td className="p-4 pr-6 text-right text-[12px] font-black text-slate-900">₹ {Number(selectedPayslip.earnings[eK]).toLocaleString()}</td>
                                            <td className="p-4 pl-6 text-[11px] font-bold text-slate-600 uppercase">{dL}</td>
                                            <td className="p-4 pr-6 text-right text-[12px] font-black text-rose-600">₹ {Number(selectedPayslip.deductions[dK]).toLocaleString()}</td>
                                        </tr>
                                    ))}
                                    <tr className="bg-slate-50 divide-x divide-slate-100">
                                        <td className="p-5 pl-6 text-[11px] font-black uppercase text-indigo-900 bg-indigo-50/20">GROSS TOTAL</td>
                                        <td className="p-5 pr-6 text-right text-[14px] font-black text-indigo-600 bg-indigo-50/20">₹ {Number(selectedPayslip.summary.grossPay).toLocaleString()}</td>
                                        <td className="p-5 pl-6 text-[11px] font-black uppercase text-rose-900 bg-rose-50/20">DEDUCTION TOTAL</td>
                                        <td className="p-5 pr-6 text-right text-[14px] font-black text-rose-600 bg-rose-50/20">₹ {Number(selectedPayslip.summary.totalDeductions).toLocaleString()}</td>
                                    </tr>
                                    <tr className="bg-slate-900 text-white">
                                        <td className="p-6 text-center font-black uppercase tracking-[0.2em] text-[12px]" colSpan={2}>
                                            NET SALARY CREDITED: ₹ {Number(selectedPayslip.summary.netSalary).toLocaleString()}
                                        </td>
                                        <td colSpan={2}></td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>

                        <div className="pt-20 flex justify-between items-end">
                            <div className="text-xs text-slate-500 font-medium space-y-1">
                                <p className="text-[10px] font-black uppercase text-slate-300 mb-6">Verified Record</p>
                                <p>On behalf of,</p>
                                <p className="pt-8 font-black text-slate-900 text-sm italic">Media Wave Technologies</p>
                                <p className="text-[10px] font-black text-indigo-600 uppercase">Automated Document Generation</p>
                            </div>
                        </div>
                    </div>
                    
                    <div className="w-full mt-auto">
                        <img src="/src/assets/payslip_footer.png" alt="Office Footer" className="w-full h-24 object-cover" />
                    </div>
                </div>
             </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default MyPayslips;
